### ISSUE TITLE
多人同屏显示

### ISSUE THREAD

**Issue by Imzsg** [tyIUc/bcandc#2]
能否减小字体实现多人消息可以同时出现在游戏中，而不是直接替换

**Comment by tyIUc** [comment]
应该是更新了

**Comment by tyIUc** [comment]
本库已作废 
请转至https://github.com/YF-OFFICE/SCPSLplugin-TextChat
下载最新

**Comment by tyIUc** [comment]
https://github.com/YF-OFFICE/SCPSLplugin-TextChat
